### ISSUE TITLE
开机一段时间后掉线

### ISSUE THREAD

**Issue by hmsjy2017** [KyonLi/ufi003-debian#2]
版本：[12.6-8](https://github.com/KyonLi/ufi003-debian/releases/tag/12.6-8)

把随身 WiFi 直接插在充电头上，运行一段时间后会出现掉线的情况（5-15分钟），ssh 无法连接，并且无法 ping 通。重新上电后恢复正常，但运行一段时间后仍会掉线。

随身 WiFi 插在电脑上时无此问题。

**Comment by KyonLi** [comment]
WiFi热点模式还是客户端

**Comment by hmsjy2017** [comment]
> WiFi热点模式还是客户端

客户端

**Comment by KyonLi** [comment]
uptime 44 min 插排自带USB口无法复现，换个非快充头试试

**Comment by hmsjy2017** [comment]
[12.6-8](https://github.com/KyonLi/ufi003-debian/releases/tag/12.6-8) 使用 5V 2A 充电头仍会有掉线问题。刷了 [12.6-7](https://github.com/KyonLi/ufi003-debian/releases/tag/12.6-7) 目前一切正常，uptime 30 min。

**Comment by KyonLi** [comment]
复现了

**Comment by KyonLi** [comment]
12.6-7的6.10.0内核同样存在此问题，降级到6.6恢复正常
